### ISSUE TITLE
Problems with Pronoun Screens

### ISSUE THREAD

**Issue by owogitcat** [xenubinx/lytelove-open#2]
![image](https://github.com/user-attachments/assets/d67c91eb-4e89-429a-b1a5-99036a765acb)
I'm stuck here. I'm not sure how to fix it...

**Comment by xenubinx** [comment]
Hey! This isn't my original code, I used a pronoun tool for renpy. It may be outdated with the newest version of renpy, so I suggest removing the pronoun folder, and finding a pronoun tool you do like and using it instead!
